spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bancogravadora
    username: pid_user
    password: Senha123.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

  jwt:
    token:
      expiration: 2
    refresh-token:
      expiration: 240

server:
  error:
    include-exception: true